### ISSUE TITLE
Add Visual Studio 2017 support

### ISSUE THREAD

**Issue by C485** [Davuskus/elevator-music-vs#2]
Like title says, i tested it and it works w/o problems

**Comment by david98hall** [comment]
I'm confused about this since the .vsixmanifest file states the following:
`<InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[16.0, 17.0)" />`
It should therefore already have support for VS 2016, VS 2017 and newer versions. When the .vsix file is uploaded to the marketplace however, the only supported version seems to be VS 2019.

**Comment by C485** [comment]
For me following settings works:
```
    <Installation>
        <InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[16.0, 17.0)" />
        <InstallationTarget Version="[15.0,16.0)" Id="Microsoft.VisualStudio.Pro" />
    </Installation>
```
`    <Prerequisites>
        <Prerequisite Id="Microsoft.VisualStudio.Component.CoreEditor" Version="[15.0,16.0)" DisplayName="Visual Studio core editor" />
    </Prerequisites>`

**Comment by david98hall** [comment]
I've updated the installation targets to VS 2017 and 2019 now. It's on the marketplace as well.

**Comment by C485** [comment]
Following nuget is missing: Microsoft.VisualStudio.Shell.15.0
It's required by VS2017
